# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Do something

on:
  push

jobs:
    do_something:
        name: Do something

        runs-on: ubuntu-latest

        environment: 
          name: staging
          url: https://github.com/elysium-everlasting/demo

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
